export const utmCampaignKey = 'utmCampaign'
export const applyPendingJobId = 'applyPendingJob'
export const isFromCreateResume = 'isFromCreateResume'
export const isGenerateResume = 'isGenerateResume'
export const appLinkUrl = 'http://bossjob.com/app'
