export const JOBBSEEKERS_LOGIN_REQUEST = 'JOBBSEEKERS_LOGIN_REQUEST'
export const JOBBSEEKERS_LOGIN_SUCCESS = 'JOBBSEEKERS_LOGIN_SUCCESS'
export const JOBBSEEKERS_LOGIN_FAILED = 'JOBBSEEKERS_LOGIN_FAILED'
