// Generated by https://quicktype.io
import {Country} from './config/location_lists';
import {JobFunctionListsType} from './config/job_function_lists'

const ConfigKeys = ['xp_lvls', 'job_types', 'degrees', 'no_of_employee_ranges', 'company_sizes', 'industry_lists', 'job_category_lists', 'job_benefit_lists', 'job_attractive_reasons', 'company_benefit_lists', 'company_culture_lists', 'company_financing_stage_lists', 'country_lists', 'location_lists', 'chat_report_lists', 'notice_period_lists', 'subscibe_job_frequency_lists', 'report_job_reasons', 'report_talent_reasons', 'salary_ranges', 'social_types', 'resume_source_lists', 'language_lists', 'gender_lists', 'pipeline_stage_lists', 'resume_last_updated_time_lists', 'job_function_lists', 'main_job_function_lists', 'report_interview_reasons', 'report_recruiter_reasons', 'report_company_reasons', 'currency_lists', 'turnover_lists', 'company_types', 'work_xps', 'educations', 'salary_range_filters', 'users', 'jobs', 'company_documents', 'recruiter_documents', 'job_seeker_work_xps', 'job_seeker_prefs', 'job_seeker_edus', 'saved_jobs', 'saved_candidates', 'blacklisted_users', 'blacklisted_companies', 'job_seeker_resumes', 'job_applications', 'dialogues', 'chats', 'interview_result', 'feature_banners', 'recruiter_role_permissions', 'recruiter_chat_type_filters', 'recruiter_chat_status_filters', 'jobseeker_chat_type_filters', 'recruiter_hot_job_title_filters', 'main_functions', 'job_functions', 'function_titles']
export type ConfigTypeKeys = typeof ConfigKeys[number];

export interface ConfigType {
	[key: ConfigTypeKeys]: any[];
	location_lists: Country[];
  job_function_lists: JobFunctionListsType;
}