export const FETCH_SIMILAR_JOBS_REQUEST = 'FETCH_SIMILAR_JOBS_REQUEST'
export const FETCH_SIMILAR_JOBS_SUCCESS = 'FETCH_SIMILAR_JOBS_SUCCESS'
export const FETCH_SIMILAR_JOBS_FAILED = 'FETCH_SIMILAR_JOBS_FAILED'
