export const FETCH_CHAT_DETAIL_REQUEST = 'FETCH_CHAT_DETAIL_REQUEST'
export const FETCH_CHAT_DETAIL_SUCCESS = 'FETCH_CHAT_DETAIL_SUCCESS'
export const FETCH_CHAT_DETAIL_FAILED = 'FETCH_CHAT_DETAIL_FAILED'
