export const FETCH_JOBS_LIST_REQUEST = 'FETCH_JOBS_LIST_REQUEST'
export const FETCH_JOBS_LIST_SUCCESS = 'FETCH_JOBS_SUCCESS'
export const FETCH_JOBS_LIST_FAILED = 'FETCH_JOBS_FAILED'
export const CLEAR_FETCH_JOBS_LIST = 'CLEAR_FETCH_JOBS_LIST'
