export const FETCH_SAVED_JOB_DETAIL_REQUEST = 'FETCH_SAVED_JOB_DETAIL_REQUEST'
export const FETCH_SAVED_JOB_DETAIL_SUCCESS = 'FETCH_SAVED_JOB_DETAIL_SUCCESS'
export const FETCH_SAVED_JOB_DETAIL_FAILED = 'FETCH_SAVED_JOB_DETAIL_FAILED'
