export const CHECK_VERIFY_EMAIL_OTP_REQUEST = 'CHECK_VERIFY_EMAIL_OTP_REQUEST'
export const CHECK_VERIFY_EMAIL_OTP_SUCCESS = 'CHECK_VERIFY_EMAIL_OTP_SUCCESS'
export const CHECK_VERIFY_EMAIL_OTP_FAILED = 'CHECK_VERIFY_EMAIL_OTP_FAILED'
