export const COMPLETE_USER_PROFILE_REQUEST = 'COMPLETE_USER_PROFILE_REQUEST'
export const COMPLETE_USER_PROFILE_SUCCESS = 'COMPLETE_USER_PROFILE_SUCCESS'
export const COMPLETE_USER_PROFILE_FAILED = 'COMPLETE_USER_PROFILE_FAILED'
