export const FETCH_USER_DETAIL_REQUEST = 'FETCH_USER_DETAIL_REQUEST'
export const FETCH_USER_DETAIL_SUCCESS = 'FETCH_USER_DETAIL_SUCCESS'
export const FETCH_USER_DETAIL_FAILED = 'FETCH_USER_DETAIL_FAILED'
