export const FETCH_USER_OWN_DETAIL_REQUEST = 'FETCH_USER_OWN_DETAIL_REQUEST'
export const FETCH_USER_OWN_DETAIL_SUCCESS = 'FETCH_USER_OWN_DETAIL_SUCCESS'
export const FETCH_USER_OWN_DETAIL_FAILED = 'FETCH_USER_OWN_DETAIL_FAILED'
