export const GENERATE_USER_RESUME_REQUEST = 'GENERATE_USER_RESUME_REQUEST'
export const GENERATE_USER_RESUME_SUCCESS = 'GENERATE_USER_RESUME_SUCCESS'
export const GENERATE_USER_RESUME_FAILED = 'GENERATE_USER_RESUME_FAILED'
