export const MANAGE_USER_LINKS_REQUEST = 'MANAGE_USER_LINKS_REQUEST'
export const MANAGE_USER_LINKS_SUCCESS = 'MANAGE_USER_LINKS_SUCCESS'
export const MANAGE_USER_LINKS_FAILED = 'MANAGE_USER_LINKS_FAILED'