export const MANAGE_USER_EDUCATIONS_REQUEST = 'MANAGE_USER_EDUCATIONS_REQUEST'
export const MANAGE_USER_EDUCATIONS_SUCCESS = 'MANAGE_USER_EDUCATIONS_SUCCESS'
export const MANAGE_USER_EDUCATIONS_FAILED = 'MANAGE_USER_EDUCATIONS_FAILED'
