export const UPLOAD_USER_RESUME_REQUEST = 'UPLOAD_USER_RESUME_REQUEST'
export const UPLOAD_USER_RESUME_SUCCESS = 'UPLOAD_USER_RESUME_SUCCESS'
export const UPLOAD_USER_RESUME_FAILED = 'UPLOAD_USER_RESUME_FAILED'
