export const FETCH_COMPANY_DETAIL_REQUEST = 'FETCH_COMPANY_DETAIL_REQUEST'
export const FETCH_COMPANY_DETAIL_SUCCESS = 'FETCH_COMPANY_DETAIL_SUCCESS'
export const FETCH_COMPANY_DETAIL_FAILED = 'FETCH_COMPANY_DETAIL_FAILED'
