export const FETCH_COMPANY_FILTER_REQUEST = 'FETCH_COMPANY_FILTER_REQUEST'
export const FETCH_COMPANY_FILTER_SUCCESS = 'FETCH_COMPANY_FILTER_SUCCESS'
export const FETCH_COMPANY_FILTER_FAILED = 'FETCH_COMPANY_FILTER_FAILED'
