export const map = {
  "xp_lvl_id": ["data", "xp_lvls"],
  "job_type_id": ["data", "job_types"],
  "degree_id": ["data", "degrees"],
  "no_of_employee_range_id": ["data", "no_of_employee_ranges"],
  "company_size_id": ["data", "company_sizes"],
  "industry_id": ["data", "industry_lists"],
  "job_category_id": ["data", "job_category_lists"],
  "job_benefit_id": ["data", "job_benefit_lists"],
  "job_attractive_reason_id": ["data", "job_attractive_reasons"],
  "company_benefit_id": ["data", "company_benefit_lists"],
  "company_culture_id": ["data", "company_culture_lists"],
  "company_financing_stage_id": ["data", "company_financing_stage_lists"],
  "country_id": ["data", "country_lists"],
  "region_id": ["data", "country_lists", "region_lists"],
  "location_id": ["data", "country_lists", "region_lists", "location_lists"],
  "chat_report_id": ["data", "chat_report_lists"],
  "notice_period_id": ["data", "notice_period_lists"],
  "subscibe_job_frequency_id": ["data", "subscibe_job_frequency_lists"],
  "report_job_reason_id": ["data", "report_job_reasons"],
  "report_talent_reason_id": ["data", "report_talent_reasons"],
  "salary_range_id": ["data", "salary_ranges"],
  "social_type_id": ["data", "social_types"],
  "resume_source_id": ["data", "resume_source_lists"],
  "language_id": ["data", "language_lists"],
  "gender_id": ["data", "gender_lists"],
  "pipeline_stage_id": ["data", "pipeline_stage_lists"],
  "resume_last_updated_time_id": ["data", "resume_last_updated_time_lists"],
  "job_function_id": ["data", "job_function_lists"],
  "report_interview_reason_id": ["data", "report_interview_reasons"],
  "report_recruiter_reason_id": ["data", "report_recruiter_reasons"],
  "currency_id": ["data", "currency_lists"],
  "work_xp_id": ["data", "work_xps"],
  "education_id": ["data", "educations"],
  "salary_range_filter_id": ["data", "salary_range_filters"],
  "user_status_id": ["data", "users"],
  "job_status_id": ["data", "jobs"],
  "company_document_status_id": ["data", "company_documents"],
  "recruiter_document_status_id": ["data", "recruiter_documents"],
  "job_seeker_work_xp_status_id": ["data", "job_seeker_work_xps"],
  "job_seeker_pref_status_id": ["data", "job_seeker_prefs"],
  "job_seeker_edu_status_id": ["data", "job_seeker_edus"],
  "saved_job_status_id": ["data", "saved_jobs"],
  "saved_candidate_status_id": ["data", "saved_candidates"],
  "blacklisted_user_status_id": ["data", "blacklisted_users"],
  "blacklisted_company_status_id": ["data", "blacklisted_companies"],
  "job_seeker_resume_status_id": ["data", "job_seeker_resumes"],
  "job_application_status_id": ["data", "job_applications"],
  "dialogue_status_id": ["data", "dialogues"],
  "chat_status_id": ["data", "chats"],
  "interview_result_status_id": ["data", "interview_result"],
  "feature_banner_id": ["data", "feature_banners"],
  "recruiter_role_permission_id": ["data", "recruiter_role_permissions"],
  "main_job_function_id": ["data", "main_job_function_lists"]
}

export const getIdPath = (key: keyof typeof map) => {
  return map[key]
}