// Generated by https://quicktype.io

export interface CompanyDetail {
  company_size:       string;
  company_size_id:    number;
  company_url:        string;
  country:            string;
  country_id:         number;
  financing_stage:    string;
  financing_stage_id: number;
  id:                 number;
  industry:           string;
  industry_id:        number;
  is_verify:          boolean;
  location:           string;
  location_id:        number;
  logo:               string;
  name:               string;
  num_of_active_jobs: number;
  logo_url:           string;
  reco_from:          string;
}
